// Code generated by protoc-gen-gogo.
// source: pb.proto
// DO NOT EDIT!

/*
Package tcprpcpb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	Message
*/
package tcprpcpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_CALL Type = 0
	Type_MSG  Type = 1
)

var Type_name = map[int32]string{
	0: "CALL",
	1: "MSG",
}
var Type_value = map[string]int32{
	"CALL": 0,
	"MSG":  1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

type Message struct {
	Type  Type   `protobuf:"varint,1,opt,name=type,proto3,enum=tcprpcpb.Type" json:"type,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Func  string `protobuf:"bytes,3,opt,name=func,proto3" json:"func,omitempty"`
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Body  []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

func (m *Message) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_CALL
}

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *Message) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "tcprpcpb.Message")
	proto.RegisterEnum("tcprpcpb.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("pb.proto", fileDescriptorPb) }

var fileDescriptorPb = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x49, 0x2e, 0x28, 0x2a, 0x48, 0x2e, 0x48, 0x52, 0xaa,
	0xe6, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x52, 0xe2, 0x62, 0x29, 0xa9, 0x2c,
	0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd3, 0x83, 0xa9, 0xd1, 0x0b, 0xa9, 0x2c,
	0x48, 0x0d, 0x02, 0xcb, 0x09, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x30,
	0x07, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xa4, 0x95, 0xe6, 0x25, 0x4b, 0x30, 0x2b, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9, 0x45, 0x45, 0xf9, 0x45, 0x12, 0x2c,
	0x60, 0x41, 0x08, 0x07, 0xa4, 0x32, 0x29, 0x3f, 0xa5, 0x52, 0x82, 0x55, 0x81, 0x51, 0x83, 0x27,
	0x08, 0xcc, 0xd6, 0x92, 0xe4, 0x62, 0x01, 0x99, 0x2d, 0xc4, 0xc1, 0xc5, 0xe2, 0xec, 0xe8, 0xe3,
	0x23, 0xc0, 0x20, 0xc4, 0xce, 0xc5, 0xec, 0x1b, 0xec, 0x2e, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0xa8,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x06, 0x9f, 0x9a, 0xb4, 0x00, 0x00, 0x00,
}
